In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import r2_score, confusion_matrix
import numpy as np
from matplotlib import pyplot as plt

In [2]:
#Importing the split data (80/20)

x_train = pd.read_csv("data/train/x_train.csv", header=0,index_col=0)
y_train = pd.read_csv("data/train/y_train.csv", header=0,index_col=0)

x_test = pd.read_csv("data/val/x_val.csv", header=0,index_col=0)
y_test = pd.read_csv("data/val/y_val.csv", header=0,index_col=0)

In [3]:
model = LogisticRegression(solver='liblinear', random_state=0)

In [4]:
model.fit(x_train,y_train)

/Users/manasavegesna/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [5]:
#prediction
y_pred = model.predict(x_test)

In [6]:
model.intercept_

array([0.3441886])

In [7]:
model.coef_

array([[-4.39204563e-17, -6.25553265e-01, -1.47732608e-01,
        -9.05520871e-02,  1.13125246e-01, -3.49688477e-02,
        -5.79914059e-03,  8.29809750e-17, -6.24718101e-01,
        -1.20938538e-01,  3.07919391e-02,  6.68965846e-02,
         1.03628594e-01,  1.16067746e-01,  8.00807191e-18,
        -6.48492161e-01,  4.94244423e-01,  5.92029534e-02,
         1.75242421e-02, -8.18472554e-02, -5.73526250e-03,
         4.39604050e-17, -6.04282563e-01, -1.64703568e+00,
         4.55003791e-01,  8.16162109e-03, -1.81419637e+00,
         7.55019658e-01,  1.46763211e-17, -6.32542307e-01,
        -2.34107478e-02, -7.16425180e-02,  1.77839113e-02,
         3.03229693e-01,  7.55417998e-01,  3.19169260e-17,
        -6.40076798e-01,  1.11774694e+00,  1.07520640e+00,
         4.38219982e-02,  1.38149289e+00,  1.05170411e+00,
        -4.38761067e-17, -6.31967600e-01, -1.09025357e-01,
        -6.40396337e-02,  1.00164795e-01, -1.61224074e-01,
        -5.10367552e-01,  4.21664094e-17, -6.74165269e-0

In [8]:
#confusion matrix

confusion_matrix(y_test, y_pred)

array([[15,  0],
       [ 3,  0]])

In [9]:
model.score(x_test,y_test)

0.8333333333333334